import Chunk, { CHUNK_SIZE, TILE_SIZE } from './Chunk.js';

export default class TileMap {
    constructor(game) {
        this.game = game;
        this.chunks = new Map(); // Key: "x,y", Value: Chunk
        this.generator = null; // Set by Game
        this.width = 0; // In tiles
        this.height = 0; // In tiles
    }

    setGenerator(generator) {
        this.generator = generator;
    }

    getChunkKey(cx, cy) {
        return `${cx},${cy}`;
    }

    getChunk(cx, cy) {
        return this.chunks.get(this.getChunkKey(cx, cy));
    }

    createChunk(cx, cy) {
        const chunk = new Chunk(cx, cy);
        this.chunks.set(this.getChunkKey(cx, cy), chunk);
        return chunk;
    }

    setTile(x, y, tileId, layer = 'floor') {
        const cx = Math.floor(x / CHUNK_SIZE);
        const cy = Math.floor(y / CHUNK_SIZE);
        const lx = x - cx * CHUNK_SIZE;
        const ly = y - cy * CHUNK_SIZE;

        let chunk = this.getChunk(cx, cy);
        if (!chunk) {
            chunk = this.createChunk(cx, cy);
        }
        chunk.setTile(lx, ly, tileId, layer);
    }

    getTile(x, y, layer = 'floor') {
        const cx = Math.floor(x / CHUNK_SIZE);
        const cy = Math.floor(y / CHUNK_SIZE);
        const lx = x - cx * CHUNK_SIZE;
        const ly = y - cy * CHUNK_SIZE;

        const chunk = this.getChunk(cx, cy);
        if (chunk) {
            return chunk.getTile(lx, ly, layer);
        }
        return null;
    }

    getTileAtWorldPos(worldX, worldY, layer = 'floor') {
        const tx = Math.floor(worldX / TILE_SIZE);
        const ty = Math.floor(worldY / TILE_SIZE);
        return this.getTile(tx, ty, layer);
    }

    isCollidable(worldX, worldY) {
        const floorId = this.getTileAtWorldPos(worldX, worldY, 'floor');
        const blockId = this.getTileAtWorldPos(worldX, worldY, 'block');

        const checkCol = (id) => {
            if (!id) return false;
            const def = this.game.assetManager.getData('tiles')?.find(t => t.id === id);
            return def ? !!def.collidable : false;
        };

        return checkCol(floorId) || checkCol(blockId);
    }

    isInteractable(worldX, worldY) {
        const tileId = this.getTileAtWorldPos(worldX, worldY);
        if (!tileId) return false;

        const tileDef = this.game.assetManager.getData('tiles')?.find(t => t.id === tileId);
        return tileDef ? !!tileDef.interactable : false;
    }

    render(ctx, camera) {
        // Calculate visible chunks based on camera
        const startCol = Math.floor(camera.x / TILE_SIZE);
        const endCol = startCol + (camera.width / TILE_SIZE) + 1;
        const startRow = Math.floor(camera.y / TILE_SIZE);
        const endRow = startRow + (camera.height / TILE_SIZE) + 1;

        const offsetX = -camera.x + camera.width / 2; // Center camera? No, usually camera.x is top-left or center.
        // Let's assume camera.x/y is the top-left corner of the viewport for now
        // Adjusted: standard 2D camera usually top-left.

        // We need to iterate through visible chunks
        const startCx = Math.floor(startCol / CHUNK_SIZE);
        const endCx = Math.floor(endCol / CHUNK_SIZE);
        const startCy = Math.floor(startRow / CHUNK_SIZE);
        const endCy = Math.floor(endRow / CHUNK_SIZE);

        for (let cy = startCy; cy <= endCy; cy++) {
            for (let cx = startCx; cx <= endCx; cx++) {
                let chunk = this.getChunk(cx, cy);
                
                // If chunk doesn't exist OR hasn't been generated by MapGenerator yet
                if ((!chunk || !chunk.isGenerated) && this.generator) {
                    this.generator.generateChunk(this, cx, cy);
                    chunk = this.getChunk(cx, cy);
                }

                if (chunk) {
                    this.renderChunk(ctx, chunk, camera);
                }
            }
        }
    }

    renderChunk(ctx, chunk, camera) {
        for (let y = 0; y < CHUNK_SIZE; y++) {
            for (let x = 0; x < CHUNK_SIZE; x++) {
                const worldX = (chunk.cx * CHUNK_SIZE + x) * TILE_SIZE;
                const worldY = (chunk.cy * CHUNK_SIZE + y) * TILE_SIZE;

                if (worldX + TILE_SIZE > camera.x && worldX < camera.x + camera.width &&
                    worldY + TILE_SIZE > camera.y && worldY < camera.y + camera.height) {
                    
                    const screenX = Math.floor(worldX - camera.x);
                    const screenY = Math.floor(worldY - camera.y);

                    // 1. Draw Floor
                    const floorId = chunk.floors[y][x];
                    if (floorId) {
                        const img = this.game.assetManager.get(floorId);
                        if (img) ctx.drawImage(img, screenX, screenY);
                    }

                    // 2. Draw Block
                    const blockId = chunk.blocks[y][x];
                    if (blockId) {
                        const img = this.game.assetManager.get(blockId);
                        if (img) ctx.drawImage(img, screenX, screenY);
                    }
                }
            }
        }
    }
}
